
version: "3"

tasks:
  generate:
    aliases: [gen]
    desc: "generate from proto file"
    cmds:
      - protoc -I protos/proto ./protos/proto/post.proto --go_out=./protos/gen/go --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go --go-grpc_opt=paths=source_relative
